image:  Ubuntu1804

install:
  - |
    chef_version='21.6.497'
    chef_url="https://packages.chef.io/files/stable/chef-workstation/${chef_version}/ubuntu/20.04/chef-workstation_${chef_version}-1_amd64.deb"
    chef_file='chef.deb'
    wget "${chef_url}" -O "${chef_file}"
    sudo dpkg -i "${chef_file}"
  - |
    vagrant_version='2.2.17'
    vagrant_url="https://releases.hashicorp.com/vagrant/${vagrant_version}/vagrant_${vagrant_version}_linux_amd64.zip"
    vagrant_file='vagrant.zip'
    wget "${vagrant_url}" -O "${vagrant_file}"
    sudo unzip -d /usr/local/bin "${vagrant_file}"
  - |
    sudo apt-get install make

build: off

test_script:
  - CHEF_LICENSE="accept" chef exec rubocop
  - make lint
  - berks install
  - chef exec rspec --fail-fast -fd
  - KITCHEN_YAML="kitchen.appveyor.yml" kitchen test --no-color --destroy=always
